FROM ultrafunk/undetected-chromedriver
COPY ../requirements.txt /opt/api/requirements.txt
WORKDIR /opt/api
RUN pip install -r requirements.txt
#RUN pip install pydantic[email]
RUN pip install -U "celery[redis]"
COPY .. /opt/api
CMD ["celery", "--app=tasks.base", "worker", "--concurrency=2", "-Q", "translate", "--loglevel=INFO"]
